# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_index', models.IntegerField(default=0)),
                ('d_name', models.CharField(max_length=100)),
                ('reg_name', models.CharField(max_length=100)),
                ('isOccupied', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
