# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zhuge_smartphone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='lastused',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
