# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zhuge_smartphone', '0002_useravatar_lastused'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='shake_val',
            field=models.IntegerField(default=0),
        ),
    ]
